name: Build and deploy ASP.Net Core app to Azure Web App - Dyspobelo

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore ./Dyspobelo.sln

      - name: Build with dotnet
        run: dotnet build --configuration Release ./Dyspobelo.sln

      - name: dotnet publish
        run: dotnet publish ./Dyspobelo/Dyspobelo.csproj -c Release -o ./myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_56DEAABFCDE943D79F97D58F66A3627D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_183AB26FFAD14EAD928E3C0C13DD6EAD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_666A295A7BF64642B9AF06BEC8C68E14 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Dyspobelo'
          slot-name: 'Production'
          package: ./myapp
